[versions]
agp = "8.6.1"
ankoSdk15 = "0.10.8"
circleimageview = "3.1.0"
klaxon = "5.5"
kotlin = "1.9.0"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.10.0"
constraintlayout = "2.2.0"
retrofit2 = "2.9.0"
converter-gson = "2.5.0"
annotation = "1.9.1"
lifecycleLivedataKtx = "2.8.7"
lifecycleViewmodelKtx = "2.8.7"
playServicesLocationVersion = "21.3.0"
mediarouter = "1.7.0"
googleGmsGoogleServices = "4.4.2"
firebaseMessaging = "24.1.0"
firebaseCrashlyticsKtx = "19.4.0"
navigationRuntimeKtx = "2.8.5"
flexbox = "3.0.0"
linphone = "5.3+"
navigation = "2.8.5"
emoji2Emojipicker = "1.5.0"
coil = "2.7.0"
googleAndroidLibrariesMapsplatformSecretsGradlePlugin = "2.0.1"
playServicesMaps = "19.0.0"
coordinatorlayout = "1.2.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
anko-sdk15 = { module = "org.jetbrains.anko:anko-sdk15", version.ref = "ankoSdk15" }
circleimageview = { module = "de.hdodenhof:circleimageview", version.ref = "circleimageview" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
klaxon = { module = "com.beust:klaxon", version.ref = "klaxon" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
retrofit = { group = 'com.squareup.retrofit2',name = "retrofit",version.ref = "retrofit2"}
coverterGson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "converter-gson"}
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
playServicesLocation = { group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocationVersion" }
androidx-mediarouter = { group = "androidx.mediarouter", name = "mediarouter", version.ref = "mediarouter" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging", version.ref = "firebaseMessaging" }
firebase-crashlytics-ktx = { group = "com.google.firebase", name = "firebase-crashlytics-ktx", version.ref = "firebaseCrashlyticsKtx" }
androidx-navigation-runtime-ktx = { group = "androidx.navigation", name = "navigation-runtime-ktx", version.ref = "navigationRuntimeKtx" }
google-flexbox = { group = "com.google.android.flexbox", name = "flexbox", version.ref = "flexbox" }
linphone = { group = "org.linphone", name = "linphone-sdk-android-debug", version.ref = "linphone" }
androidx-emoji2-emojipicker = { group = "androidx.emoji2", name = "emoji2-emojipicker", version.ref = "emoji2Emojipicker" }
coil = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
coil-gif = { group = "io.coil-kt", name = "coil-gif", version.ref = "coil" }
coil-svg = { group = "io.coil-kt", name = "coil-svg", version.ref = "coil" }
coil-video = { group = "io.coil-kt", name = "coil-video", version.ref = "coil" }
play-services-maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "playServicesMaps" }
androidx-coordinatorlayout = { group = "androidx.coordinatorlayout", name = "coordinatorlayout", version.ref = "coordinatorlayout" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
navigation = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }
google-android-libraries-mapsplatform-secrets-gradle-plugin = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "googleAndroidLibrariesMapsplatformSecretsGradlePlugin" }